title: "Kirill Zaitsev"
author: "Kirill Zaitsev"
description: >-
  Projects in machine learning, big data, and software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

linkedin_username: "kirill-zaitsev-"
github_username: "kirilllzaitsev"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


kramdown:
  syntax_highlighter_opts:
    disable: true
    
titles_from_headings:
  strip_title: true
  collections: true

google_analytics: "G-9ZY73TQK0J"

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags:
      - Other

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/